puts "What are you considering to buy? Notice, this is only a general recommendation."
    puts "1. CPU + Motherboard"
    puts "2. GPU"
    puts "3. Storage solutions"
    puts "4. Full PC"
print "Your answer: "
    answer = gets.chomp

if answer == "1"
    puts "What are you planning to do with this upgrade?"
        puts "1. Purely more gaming performance"
        puts "2. Content creation"
        puts "3. Just purely better Microsoft Office performance"
        puts "4. Code compilation improvements"
        puts "5. Hackintoshing"
    print "Your answer: "
    answer_1 = gets.chomp
        if answer_1 == "1"
            puts "Do you have any brand preferences?"
                puts "1. AMD"
                puts "2. Intel"
                puts "3. Either's fine"
            print "Your answer: "
                answer_cpubrand = gets.chomp 
                    if answer_cpubrand == "1"
                        puts "You can buy a Ryzen 5 3600 and you'd be satisfied with it. Probably the best bang for the buck right now. Though, Ryzen 5000 is coming out soon, so you might want to wait for that instead."
                    elsif answer_cpubrand == "2"
                        puts "Probably your best bet is an i5-10600K. Usually for gaming, this is all you'd need"
                    elsif answer_cpubrand == "3"
                        puts "Either a Ryzen 5 3600 or an i5-10400 would be fine for what you need"
                    end
        elsif answer_1 == "2"
            puts "Do you have any brand preferences?"
                puts "1. AMD"
                puts "2. Intel"
                puts "3. Either's fine"
            print "Your answer: "
                answer_cpubrand = gets.chomp 
                    if answer_cpubrand == "1"
                        puts "You can buy a Ryzen 5 3600 and you'd be satisfied with it. Probably the best bang for the buck right now. Though, Ryzen 5000 is coming out soon, so you might want to wait for that instead."
                    elsif answer_cpubrand == "2"
                        puts "Probably your best bet is an i5-10600K. Usually for gaming, this is all you'd need"
                    elsif answer_cpubrand == "3"
                        puts "Either a Ryzen 5 3600 or an i5-10400 would be fine for what you need"
                    end
        elsif answer_1 == "3"
           puts ""
        elsif answer_1 == "4"
            puts "Do you have any brand preferences?"
                puts "1. AMD"
                puts "2. Intel"
                puts "3. Either's fine"
            print "Your answer: "
                answer_cpubrand = gets.chomp 
                    if answer_cpubrand == "1"
                        puts "You can buy a Ryzen 5 3600 and you'd be satisfied with it. Probably the best bang for the buck right now. Though, Ryzen 5000 is coming out soon, so you might want to wait for that instead."
                    elsif answer_cpubrand == "2"
                        puts "Probably your best bet is an i5-10600K. Usually for gaming, this is all you'd need"
                    elsif answer_cpubrand == "3"
                        puts "Either a Ryzen 5 3600 or an i5-10400 would be fine for what you need"
                    end
        elsif answer_1 == "5"
            puts "You can "
        end